### Get all albums
GET http://localhost:8080/api/albums
Accept: application/json

### Get an album with the given id
GET localhost:8080/api/albums/1

### Delete a album with the given id.
DELETE localhost:8080/api/albums/1


###Post a new album
POST http://localhost:8080/api/albums
Content-Type: application/json

{
  "albumName": "Melon Collie and the Infinite Sadness",
  "image": "/src/images/sp.jpg",
  "artist": "Smashing Pumpkins",
  "recordLabel": "Virgin"
}

### Add a Song
PATCH http://localhost:8080/api/albums/2/songs
Content-Type: application/json

{
  "songName": "New Song",
  "image": "New Image",
  "playTime": "New Play Time",
  "artist": "New Artist"
}
