const allAlbums = [{
        albumName: "Rage Against the Machine",
        image: "/frontend-spa/src/img/ratm_rageagainst_cd (1).jpg",
        artist: "Rage Against the Machine",
        recordLabel: "Epic",
        songs: [{
                songName: "Killing in the Name",
                artist: "Rage Against the Machine",
                playTime: "05:14",
                image: "/frontend-spa/src/img/ratm_rageagainst_cd (1).jpg",
                id: 5,
            },
            {
                songName: "Fistful of Steel",
                artist: "Rage Against the Machine",
                playTime: "05:31",
                image: "/frontend-spa/src/img/ratm_rageagainst_cd (1).jpg",
                id: 11,
            },
            {
                songName: "Bombtrack",
                artist: "Rage Against the Machine",
                playTime: "04:04",
                image: "/frontend-spa/src/img/ratm_rageagainst_cd (1).jpg",
                id: 4,
            },
            {
                songName: "Settle for Nothing",
                artist: " Rage Against the Machine",
                playTime: "04:48",
                image: "/frontend-spa/src/img/ratm_rageagainst_cd (1).jpg",
                id: 7,
            },
            {
                songName: "Freedom",
                artist: "Rage Against the Machine",
                playTime: "06:06",
                image: "/frontend-spa/src/img/ratm_rageagainst_cd (1).jpg",
                id: 13,
            },
            {
                songName: "Take the Power Back",
                artist: "Rage Against the Machine",
                playTime: "05:37",
                image: "/frontend-spa/src/img/ratm_rageagainst_cd (1).jpg",
                id: 6,
            },
            {
                songName: "Wake Up",
                artist: "Rage Against the Machine",
                playTime: "06:04",
                image: "/frontend-spa/src/img/ratm_rageagainst_cd (1).jpg",
                id: 10,
            },
            {
                songName: "Bullet in the Head",
                artist: "Rage Against the Machine",
                playTime: "05:09",
                image: "/frontend-spa/src/img/ratm_rageagainst_cd (1).jpg",
                id: 8,
            },
            {
                songName: "Township Rebellion",
                artist: "Rage Against the Machine",
                playTime: "05:24",
                image: "/frontend-spa/src/img/ratm_rageagainst_cd (1).jpg",
                id: 12,
            },
            {
                songName: "Know Your Enemy",
                artist: "Rage Against the Machine",
                playTime: "04:55",
                image: "/frontend-spa/src/img/ratm_rageagainst_cd (1).jpg",
                id: 9,
            },
        ],
        id: 1,
    },
    {
        albumName: "Jagged Little Pill",
        image: "/frontend-spa/src/img/hitchhiker-symbol-icon.png",
        artist: "Alanis Morissette",
        recordLabel: "Maverick",
        songs: [{
                songName: "You Learn",
                artist: "Alanis Morissette",
                playTime: "4:00",
                image: "/frontend-spa/src/img/hitchhiker-symbol-icon.png",
                id: 20,
            },
            {
                songName: "Forgiven",
                artist: "Alanis Morissette",
                playTime: "5:00",
                image: "/src/images/am-song.png",
                id: 19,
            },
            {
                songName: "All I Really Want",
                artist: "Alanis Morissette",
                playTime: "4:45",
                image: "/src/images/am-song.png",
                id: 14,
            },
            {
                songName: "You Oughta Know",
                artist: "Alanis Morissette",
                playTime: "4:09",
                image: "/src/images/am-song.png",
                id: 15,
            },
            {
                songName: "Ironic",
                artist: "Alanis Morissette",
                playTime: "3:50",
                image: "/src/images/am-song.png",
                id: 23,
            },
            {
                songName: "You Oughta Know (Jimmy the Saint Blend)",
                artist: "Alanis Morissette",
                playTime: "8:13",
                image: "/src/images/am-song.png",
                id: 26,
            },
            {
                songName: "Perfect",
                artist: "Alanis Morissette",
                playTime: "3:08",
                image: "/src/images/am-song.png",
                id: 16,
            },
            {
                songName: "Right Through You",
                artist: "Alanis Morissette",
                playTime: "2:56",
                image: "/src/images/am-song.png",
                id: 18,
            },
            {
                songName: "Head Over Feet",
                artist: "Alanis Morissette",
                playTime: "4:27",
                image: "/src/images/am-song.png",
                id: 21,
            },
            {
                songName: "Not the Doctor",
                artist: "Alanis Morissette",
                playTime: "3:48",
                image: "/src/images/am-song.png",
                id: 24,
            },
            {
                songName: "Hand in My Pocket",
                artist: "Alanis Morissette",
                playTime: "3:42",
                image: "/src/images/am-song.png",
                id: 17,
            },
            {
                songName: "Wake Up",
                artist: "Alanis Morissette",
                playTime: "4:54",
                image: "/src/images/am-song.png",
                id: 25,
            },
            {
                songName: "Mary Jane",
                artist: "Alanis Morissette",
                playTime: "4:41",
                image: "/src/images/am-song.png",
                id: 22,
            },
        ],
        id: 2,
    },
    {
        albumName: "amo",
        image: "/src/images/bmth.png",
        artist: "Bring Me The Horizon",
        recordLabel: "Sony",
        songs: [{
                songName: "Wonderful Life",
                artist: "Bring Me The Horizon",
                playTime: "4:34",
                image: "/src/images/bmth-song.png",
                id: 31,
            },
            {
                songName: "Medicine",
                artist: "Bring Me The Horizon",
                playTime: "3:47",
                image: "/src/images/bmth-song.png",
                id: 33,
            },
            {
                songName: "Heavy Metal",
                artist: "Bring Me The Horizon",
                playTime: "4:00",
                image: "/src/images/bmth-song.png",
                id: 38,
            },
            {
                songName: "In the Dark",
                artist: "Bring Me The Horizon",
                playTime: "4:31",
                image: "/src/images/bmth-song.png",
                id: 30,
            },
            {
                songName: "I Apologise If You Feel Something",
                artist: "Bring Me The Horizon",
                playTime: "2:19",
                image: "/src/images/bmth-song.png",
                id: 27,
            },
            {
                songName: "Nihilist Blues",
                artist: "Bring Me The Horizon",
                playTime: "5:25",
                image: "/src/images/bmth-song.png",
                id: 29,
            },
            {
                songName: "Sugar Honey Ice & Tea",
                artist: "Bring Me The Horizon",
                playTime: "4:21",
                image: "/src/images/bmth-song.png",
                id: 34,
            },
            {
                songName: "Fresh Bruises",
                artist: "Bring Me The Horizon",
                playTime: "3:18",
                image: "/src/images/bmth-song.png",
                id: 36,
            },
            {
                songName: "Ouch",
                artist: "Bring Me The Horizon",
                playTime: "1:49",
                image: "/src/images/bmth-song.png",
                id: 32,
            },
            {
                songName: "Why You Gotta Kick Me When I'm Down?",
                artist: "Bring Me The Horizon",
                playTime: "4:28",
                image: "/src/images/bmth-song.png",
                id: 35,
            },
            {
                songName: "Mother Tongue",
                artist: "Bring Me The Horizon",
                playTime: "3:37",
                image: "/src/images/bmth-song.png",
                id: 37,
            },
            {
                songName: "Mantra",
                artist: "Bring Me The Horizon",
                playTime: "3:53",
                image: "/src/images/bmth-song.png",
                id: 28,
            },
            {
                songName: "I Don't Know What to Say",
                artist: "Bring Me The Horizon",
                playTime: "5:52",
                image: "/src/images/bmth-song.png",
                id: 39,
            },
        ],
        id: 3,
    },
]
export { allAlbums }